Mon Nov 05 20:53:49 EST 2018 : Apache Derby Network Server - 10.11.1.2 - (1629631) started and ready to accept connections on port 1527
----------------------------------------------------------------
Mon Nov 05 20:53:49 EST 2018:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a816c00e-0166-e6b9-cf8e-00001fc45bb8 
on database directory /Users/pittsfirstbeauty/Downloads/DerbyWeb2/DBMS/guojing with class loader sun.misc.Launcher$AppClassLoader@5e481248 
Loaded from file:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b12
user.dir=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/db
os.name=Mac OS X
os.arch=x86_64
os.version=10.13.6
derby.system.home=/Users/pittsfirstbeauty/Downloads/DerbyWeb2/DBMS
Database Class Loader started - derby.database.classpath=''
----------------------------------------------------------------
Mon Nov 05 20:53:50 EST 2018:
Shutting down instance a816c00e-0166-e6b9-cf8e-00001fc45bb8 on database directory /Users/pittsfirstbeauty/Downloads/DerbyWeb2/DBMS/guojing with class loader sun.misc.Launcher$AppClassLoader@5e481248 
Mon Nov 05 20:53:50 EST 2018 Thread[DRDAConnThread_3,5,main] (DATABASE = guojing), (DRDAID = {2}), Database 'guojing' shutdown.
----------------------------------------------------------------
Mon Nov 05 20:54:05 EST 2018:
Booting Derby version The Apache Software Foundation - Apache Derby - 10.11.1.2 - (1629631): instance a65c80ac-0166-e6b9-cf8e-00001fc45bb8 
on database directory /Users/pittsfirstbeauty/Downloads/DerbyWeb2/DBMS/guojing with class loader sun.misc.Launcher$AppClassLoader@5e481248 
Loaded from file:/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/db/lib/derby.jar
java.vendor=Oracle Corporation
java.runtime.version=1.8.0_161-b12
user.dir=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/db
os.name=Mac OS X
os.arch=x86_64
os.version=10.13.6
derby.system.home=/Users/pittsfirstbeauty/Downloads/DerbyWeb2/DBMS
Database Class Loader started - derby.database.classpath=''
Mon Nov 05 20:57:09 EST 2018 Thread[DRDAConnThread_3,5,main] (XID = 309), (SESSIONID = 2), (DATABASE = guojing), (DRDAID = {4}), Cleanup action starting
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
Caused by: ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	... 18 more
============= begin nested exception, level (1) ===========
ERROR 08004: Connection authentication failure occurred.  Reason: Invalid authentication..
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.wrapArgsForTransportAcrossDRDA(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.getNewEmbedConnection(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
	at org.apache.derby.jdbc.EmbeddedDriver.connect(Unknown Source)
	at org.apache.derby.impl.drda.Database.makeConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.getConnFromDatabaseName(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.verifyUserIdPassword(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseSECCHK(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.parseDRDAConnection(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.processCommands(Unknown Source)
	at org.apache.derby.impl.drda.DRDAConnThread.run(Unknown Source)
============= end nested exception, level (1) ===========
Cleanup action completed
Mon Nov 05 20:57:09 EST 2018 Thread[DRDAConnThread_3,5,main] (DATABASE = guojing), (DRDAID = {4}), Connection authentication failure occurred.  Reason: Invalid authentication..
